[project]
name = ""
version = ""
description = ""
authors = [
    {name = "MatheusGobetti", email = "gobetti.ifc@gmail.com"},
]
dependencies = [
    "django>=4.2.4",
    "djangorestframework>=3.14.0",
    "djangorestframework-simplejwt>=5.3.0",
]
requires-python = ">=3.10"
license = {text = "MIT"}
