# Generated by Django 4.1.7 on 2023-03-28 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0008_remove_veiculo_categoria_remove_veiculo_cor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='categoria',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, related_name='Veiculos', to='garagem.categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veiculo',
            name='cor',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, related_name='Veiculos', to='garagem.cor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veiculo',
            name='marca',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, related_name='Veiculos', to='garagem.marca'),
            preserve_default=False,
        ),
    ]
