# Generated by Django 4.2.4 on 2023-08-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0010_alter_acessorio_options_alter_veiculo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='acessorio',
            field=models.ManyToManyField(related_name='veiculo', to='garagem.acessorio'),
        ),
    ]
